### ISSUE TITLE
Persist Auth0 tokens between screen refreshes

### ISSUE THREAD

**Issue by gsong** [xiaozhong21/StockSimplified#13]
See https://github.com/gsong/express-react-project-starter/pull/44/commits/39e106dd20d1a44cfbcc6b54fdc3f7088c65209d for more details.

**Comment by xiaozhong21** [comment]
> See [gsong/express-react-project-starter@39e106d](https://github.com/gsong/express-react-project-starter/commit/39e106dd20d1a44cfbcc6b54fdc3f7088c65209d) for more details.

Thank you George! Just made the changes: https://github.com/xiaozhong21/StockSimplified/pull/8/commits/967003ff95a83f65f4a68faec1521865fbb242bf

**Comment by xiaozhong21** [comment]
See https://github.com/xiaozhong21/StockSimplified/pull/8/commits/967003ff95a83f65f4a68faec1521865fbb242bf
